In [1]:
#importing the libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
datasets=pd.read_csv("Social_Network_Ads.csv")

In [3]:
datasets

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
datasets=pd.get_dummies(datasets,drop_first=True)

In [5]:
datasets

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
datasets=datasets.drop("User ID",axis=1)

In [7]:
datasets["Purchased"].value_counts()


0    257
1    143
Name: Purchased, dtype: int64

In [8]:
indep=datasets[["Age","EstimatedSalary","Gender_Male"]]
dep=datasets["Purchased"]

In [9]:
indep

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [10]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [12]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)



from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,)
print("The f1_macro value for best parameter {}:",f1_macro)

from sklearn.metrics import accuracy_score
accuracy_score=accuracy_score(y_test,y_pred)
print("The accuracy_score value for best parameter {}:",accuracy_score)

from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score=balanced_accuracy_score(y_test,y_pred)
print("The balanced_accuracy_score for best parameter {}:",balanced_accuracy_score)

from sklearn.metrics import top_k_accuracy_score
top_k_accuracy_score=top_k_accuracy_score(y_test,y_pred, k=2)
print("The top_k_accuracy_score for best parameter {}:",top_k_accuracy_score)

from sklearn.metrics import average_precision_score
average_precision_score=average_precision_score(y_test, y_pred)
print("The average_precision_score value for best parameter {}:",average_precision_score)

from sklearn.metrics import brier_score_loss
brier_score_loss=brier_score_loss(y_test, y_pred)
print("The brier_score_loss for best parameter {}:",brier_score_loss)

from sklearn.metrics import log_loss
log_loss=log_loss(y_test,y_pred)
print("The log_loss for best parameter {}:",log_loss)

from sklearn.metrics import precision_score
precision_score=precision_score(y_test,y_pred)
print("The precision_score for best parameter {}:",precision_score)

from sklearn.metrics import recall_score
recall_score=recall_score(y_test,y_pred)
print("The recall_score for best parameter {}:",recall_score)

from sklearn.metrics import jaccard_score
jaccard_score=jaccard_score(y_test,y_pred)
print("The jaccard_score for best parameter {}:",jaccard_score)


              precision    recall  f1-score   support

           0       0.90      0.94      0.92        79
           1       0.87      0.80      0.84        41

    accuracy                           0.89       120
   macro avg       0.89      0.87      0.88       120
weighted avg       0.89      0.89      0.89       120

[[74  5]
 [ 8 33]]
The f1_macro value for best parameter {}: 0.8354430379746836
The accuracy_score value for best parameter {}: 0.8916666666666667
The balanced_accuracy_score for best parameter {}: 0.8707934547699907
The top_k_accuracy_score for best parameter {}: 1.0
The average_precision_score value for best parameter {}: 0.7656397090286693
The brier_score_loss for best parameter {}: 0.10833333333333334
The log_loss for best parameter {}: 3.7417340926749163
The precision_score for best parameter {}: 0.868421052631579
The recall_score for best parameter {}: 0.8048780487804879
The jaccard_score for best parameter {}: 0.717391304347826


C:\Users\rajah\anaconda3\envs\pugazh\lib\site-packages\sklearn\metrics\_ranking.py:1745: UndefinedMetricWarning: 'k' (2) greater than or equal to 'n_classes' (2) will result in a perfect score and is therefore meaningless.
  UndefinedMetricWarning,


In [13]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,)
print("The f1_macro value for best parameter {}:",f1_macro)

from sklearn.metrics import accuracy_score
accuracy_score=accuracy_score(y_test,y_pred)
print("The accuracy_score value for best parameter {}:",accuracy_score)

from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score=balanced_accuracy_score(y_test,y_pred)
print("The balanced_accuracy_score for best parameter {}:",balanced_accuracy_score)

from sklearn.metrics import top_k_accuracy_score
top_k_accuracy_score=top_k_accuracy_score(y_test,y_pred, k=2)
print("The top_k_accuracy_score for best parameter {}:",top_k_accuracy_score)

from sklearn.metrics import average_precision_score
average_precision_score=average_precision_score(y_test, y_pred)
print("The average_precision_score value for best parameter {}:",average_precision_score)

from sklearn.metrics import brier_score_loss
brier_score_loss=brier_score_loss(y_test, y_pred)
print("The brier_score_loss for best parameter {}:",brier_score_loss)

from sklearn.metrics import log_loss
log_loss=log_loss(y_test,y_pred)
print("The log_loss for best parameter {}:",log_loss)

from sklearn.metrics import precision_score
precision_score=precision_score(y_test,y_pred)
print("The precision_score for best parameter {}:",precision_score)

from sklearn.metrics import recall_score
recall_score=recall_score(y_test,y_pred)
print("The recall_score for best parameter {}:",recall_score)

from sklearn.metrics import jaccard_score
jaccard_score=jaccard_score(y_test,y_pred)
print("The jaccard_score for best parameter {}:",jaccard_score)



              precision    recall  f1-score   support

           0       0.71      0.86      0.78        79
           1       0.54      0.32      0.40        41

    accuracy                           0.68       120
   macro avg       0.62      0.59      0.59       120
weighted avg       0.65      0.68      0.65       120

[[68 11]
 [28 13]]
The f1_macro value for best parameter {}: 0.39999999999999997
The accuracy_score value for best parameter {}: 0.675
The balanced_accuracy_score for best parameter {}: 0.5889163322012967
The top_k_accuracy_score for best parameter {}: 1.0
The average_precision_score value for best parameter {}: 0.4050813008130081
The brier_score_loss for best parameter {}: 0.325
The log_loss for best parameter {}: 11.225175624777073
The precision_score for best parameter {}: 0.5416666666666666
The recall_score for best parameter {}: 0.3170731707317073
The jaccard_score for best parameter {}: 0.25


C:\Users\rajah\anaconda3\envs\pugazh\lib\site-packages\sklearn\metrics\_ranking.py:1745: UndefinedMetricWarning: 'k' (2) greater than or equal to 'n_classes' (2) will result in a perfect score and is therefore meaningless.
  UndefinedMetricWarning,


In [14]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,)
print("The f1_macro value for best parameter {}:",f1_macro)

from sklearn.metrics import accuracy_score
accuracy_score=accuracy_score(y_test,y_pred)
print("The accuracy_score value for best parameter {}:",accuracy_score)

from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score=balanced_accuracy_score(y_test,y_pred)
print("The balanced_accuracy_score for best parameter {}:",balanced_accuracy_score)

from sklearn.metrics import top_k_accuracy_score
top_k_accuracy_score=top_k_accuracy_score(y_test,y_pred, k=2)
print("The top_k_accuracy_score for best parameter {}:",top_k_accuracy_score)

from sklearn.metrics import average_precision_score
average_precision_score=average_precision_score(y_test, y_pred)
print("The average_precision_score value for best parameter {}:",average_precision_score)

from sklearn.metrics import brier_score_loss
brier_score_loss=brier_score_loss(y_test, y_pred)
print("The brier_score_loss for best parameter {}:",brier_score_loss)

from sklearn.metrics import log_loss
log_loss=log_loss(y_test,y_pred)
print("The log_loss for best parameter {}:",log_loss)

from sklearn.metrics import precision_score
precision_score=precision_score(y_test,y_pred)
print("The precision_score for best parameter {}:",precision_score)

from sklearn.metrics import recall_score
recall_score=recall_score(y_test,y_pred)
print("The recall_score for best parameter {}:",recall_score)

from sklearn.metrics import jaccard_score
jaccard_score=jaccard_score(y_test,y_pred)
print("The jaccard_score for best parameter {}:",jaccard_score)



C:\Users\rajah\anaconda3\envs\pugazh\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rajah\anaconda3\envs\pugazh\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rajah\anaconda3\envs\pugazh\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rajah\anac

              precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120

[[79  0]
 [41  0]]
The f1_macro value for best parameter {}: 0.0
The accuracy_score value for best parameter {}: 0.6583333333333333
The balanced_accuracy_score for best parameter {}: 0.5
The top_k_accuracy_score for best parameter {}: 1.0
The average_precision_score value for best parameter {}: 0.3416666666666667
The brier_score_loss for best parameter {}: 0.3416666666666667
The log_loss for best parameter {}: 11.800748601594483
The precision_score for best parameter {}: 0.0
The recall_score for best parameter {}: 0.0
The jaccard_score for best parameter {}: 0.0


C:\Users\rajah\anaconda3\envs\pugazh\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
from sklearn.naive_bayes import ComplementNB
classifier =ComplementNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,)
print("The f1_macro value for best parameter {}:",f1_macro)

from sklearn.metrics import accuracy_score
accuracy_score=accuracy_score(y_test,y_pred)
print("The accuracy_score value for best parameter {}:",accuracy_score)

from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score=balanced_accuracy_score(y_test,y_pred)
print("The balanced_accuracy_score for best parameter {}:",balanced_accuracy_score)

from sklearn.metrics import top_k_accuracy_score
top_k_accuracy_score=top_k_accuracy_score(y_test,y_pred, k=2)
print("The top_k_accuracy_score for best parameter {}:",top_k_accuracy_score)

from sklearn.metrics import average_precision_score
average_precision_score=average_precision_score(y_test, y_pred)
print("The average_precision_score value for best parameter {}:",average_precision_score)

from sklearn.metrics import brier_score_loss
brier_score_loss=brier_score_loss(y_test, y_pred)
print("The brier_score_loss for best parameter {}:",brier_score_loss)

from sklearn.metrics import log_loss
log_loss=log_loss(y_test,y_pred)
print("The log_loss for best parameter {}:",log_loss)

from sklearn.metrics import precision_score
precision_score=precision_score(y_test,y_pred)
print("The precision_score for best parameter {}:",precision_score)

from sklearn.metrics import recall_score
recall_score=recall_score(y_test,y_pred)
print("The recall_score for best parameter {}:",recall_score)

from sklearn.metrics import jaccard_score
jaccard_score=jaccard_score(y_test,y_pred)
print("The jaccard_score for best parameter {}:",jaccard_score)



              precision    recall  f1-score   support

           0       0.68      0.53      0.60        79
           1       0.36      0.51      0.42        41

    accuracy                           0.53       120
   macro avg       0.52      0.52      0.51       120
weighted avg       0.57      0.52      0.54       120

[[42 37]
 [20 21]]
The f1_macro value for best parameter {}: 0.42424242424242425
The accuracy_score value for best parameter {}: 0.525
The balanced_accuracy_score for best parameter {}: 0.5219203457857363
The top_k_accuracy_score for best parameter {}: 1.0
The average_precision_score value for best parameter {}: 0.352116624614522
The brier_score_loss for best parameter {}: 0.475
The log_loss for best parameter {}: 16.40616533012355
The precision_score for best parameter {}: 0.3620689655172414
The recall_score for best parameter {}: 0.5121951219512195
The jaccard_score for best parameter {}: 0.2692307692307692


C:\Users\rajah\anaconda3\envs\pugazh\lib\site-packages\sklearn\metrics\_ranking.py:1745: UndefinedMetricWarning: 'k' (2) greater than or equal to 'n_classes' (2) will result in a perfect score and is therefore meaningless.
  UndefinedMetricWarning,


In [16]:
from sklearn.naive_bayes import CategoricalNB
classifier =CategoricalNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,)
print("The f1_macro value for best parameter {}:",f1_macro)

from sklearn.metrics import accuracy_score
accuracy_score=accuracy_score(y_test,y_pred)
print("The accuracy_score value for best parameter {}:",accuracy_score)

from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score=balanced_accuracy_score(y_test,y_pred)
print("The balanced_accuracy_score for best parameter {}:",balanced_accuracy_score)

from sklearn.metrics import top_k_accuracy_score
top_k_accuracy_score=top_k_accuracy_score(y_test,y_pred, k=2)
print("The top_k_accuracy_score for best parameter {}:",top_k_accuracy_score)

from sklearn.metrics import average_precision_score
average_precision_score=average_precision_score(y_test, y_pred)
print("The average_precision_score value for best parameter {}:",average_precision_score)

from sklearn.metrics import brier_score_loss
brier_score_loss=brier_score_loss(y_test, y_pred)
print("The brier_score_loss for best parameter {}:",brier_score_loss)

from sklearn.metrics import log_loss
log_loss=log_loss(y_test,y_pred)
print("The log_loss for best parameter {}:",log_loss)

from sklearn.metrics import precision_score
precision_score=precision_score(y_test,y_pred)
print("The precision_score for best parameter {}:",precision_score)

from sklearn.metrics import recall_score
recall_score=recall_score(y_test,y_pred)
print("The recall_score for best parameter {}:",recall_score)

from sklearn.metrics import jaccard_score
jaccard_score=jaccard_score(y_test,y_pred)
print("The jaccard_score for best parameter {}:",jaccard_score)



              precision    recall  f1-score   support

           0       0.89      0.96      0.93        79
           1       0.91      0.78      0.84        41

    accuracy                           0.90       120
   macro avg       0.90      0.87      0.88       120
weighted avg       0.90      0.90      0.90       120

[[76  3]
 [ 9 32]]
The f1_macro value for best parameter {}: 0.8421052631578947
The accuracy_score value for best parameter {}: 0.9
The balanced_accuracy_score for best parameter {}: 0.8712565606668725
The top_k_accuracy_score for best parameter {}: 1.0
The average_precision_score value for best parameter {}: 0.788588850174216
The brier_score_loss for best parameter {}: 0.1
The log_loss for best parameter {}: 3.4538976294268244
The precision_score for best parameter {}: 0.9142857142857143
The recall_score for best parameter {}: 0.7804878048780488
The jaccard_score for best parameter {}: 0.7272727272727273


C:\Users\rajah\anaconda3\envs\pugazh\lib\site-packages\sklearn\metrics\_ranking.py:1745: UndefinedMetricWarning: 'k' (2) greater than or equal to 'n_classes' (2) will result in a perfect score and is therefore meaningless.
  UndefinedMetricWarning,
